
from t2listing import *
import numpy as np
import matplotlib.pyplot as plt
import csv
import os
from t2data import *
from mpl_toolkits.mplot3d import Axes3D

liq_density_kgPm3=1000
water_molecular_weight=0.018
R_value=8.314
m2mm=1000
day2s=3600*24
T_kelven=273.15
Pa2Kpa=1000

i=0
while i<lst.num_times:

    # Liquid_flow_raw            = lst.connection['FLO(LIQ.)']/dat.grid.connectionlist[0].area/liq_density_kgPm3*m2mm*day2s
    # Liquid_flow                = np.insert(Liquid_flow_raw,0, Liquid_flow_raw[-1])
    # Gas_flow_raw               = lst.connection['FLO(GAS)']/dat.grid.connectionlist[0].area/liq_density_kgPm3*m2mm*day2s
    # Gas_flow                   = np.insert(Gas_flow_raw,0, Gas_flow_raw[-1])

    fig=plt.figure(figsize=(12,15))
    fig.subplots_adjust(hspace=.30,wspace=.2)
    fig.subplots_adjust(left=0.07, right=0.93, top=0.93, bottom=0.05)
	
    ax11=plt.subplot(331)
    ax11.plot(Liq_saturation[:,i]*100,element_value,'k1-')
    plt.ylabel('x (m)')
    plt.xlabel('Liq. sat. (%)')
    # plt.ylabel('high (m)')
    plt.ylim(5.5,-0.5)
    plt.xlim(-5,105)
    #ax11.set_yscale('log')   
    ax13=ax11.twiny()	
    ax13.plot(Temperature[:,i],element_value,'r1-')
    plt.xlabel('Tem. (Degree)')
    # plt.ylabel('high (m)')
    plt.ylim(5.5,-0.5)
    plt.xlim(12.95,13.05)
    #plt.xlim(np.min(Temperature),np.max(Temperature))
    #ax13.set_yscale('log')
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0)) 
    ax13.spines['top'].set_color('red')
    ax13.xaxis.label.set_color('red')
    ax13.tick_params(axis='x', colors='red')
	
    ax9=plt.subplot(332)
    ax9.plot(Gas_permeability[:,i],element_value,'k1-')
    #plt.ylabel('x (m)')
    plt.xlabel('Gas. Rel. K')
    # plt.ylabel('high (m)')
    plt.ylim(5.5,-0.5)
    plt.xlim(-0.05,1.05)
    #plt.xlim(np.min(Gas_permeability),np.max(Gas_permeability))
    plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0)) 
    ax10=ax9.twiny()	
    ax10.plot(Liq_permeability[:,i],element_value,'r1-')
    plt.xlabel('Liq. Rel. K')
    # plt.ylabel('high (m)')
    plt.ylim(5.5,-0.5)
    plt.xlim(-0.05,1.05)
    #plt.xlim(np.min(Liq_permeability),np.max(Liq_permeability))
    #ax13.set_yscale('log')
    plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0)) 
    ax10.spines['top'].set_color('red')
    ax10.xaxis.label.set_color('red')
    ax10.tick_params(axis='x', colors='red')

    ax1=plt.subplot(334)
    ax1.plot(Gas_Pressure[:,i]/Pa2Kpa, element_value,'k1-')
    plt.xlabel('Gas. Pre. (Kpa)')
    #ax1.spines['top'].set_color('red')
    plt.ylim(5.5,-0.5)
    plt.xlim(50,400)
    #plt.xlim(np.min(Gas_Pressure/Pa2Kpa),np.max(Gas_Pressure/Pa2Kpa))
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    #ax1.set_yscale('log')
    ax2=ax1.twiny()
    ax2.plot(Gas_flow_raw[:,i]*10,connection_value,'r1-')
    plt.xlabel('Gas Vel. ($*10^-1$ mm/day)')
    # plt.ylabel('high (m)')
    plt.ylim(5.5,-0.5)
    plt.xlim(-1.2,1.3)
    #plt.xlim(np.min(Gas_flow_raw*10),np.max(Gas_flow_raw*10))
    #ax2.set_yscale('log')
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    ax2.spines['top'].set_color('red')
    ax2.xaxis.label.set_color('red')
    ax2.tick_params(axis='x', colors='red')	 

    ax3=plt.subplot(335)
    ax3.plot(Capillary_Pressure[:,i]/Pa2Kpa/1.e4,element_value,'k1-')
    plt.xlabel('Cap. pre. ($*10^4$ Kpa)')
    # plt.ylabel('high (m)')
    plt.ylim(5.5,-0.5)
    plt.xlim(-5,0.1)
    #plt.xlim(np.min(Gas_flow_raw),np.max(Gas_flow_raw))
    #ax3.set_yscale('log')
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))	
    ax4=ax3.twiny()	
    ax4.plot(Liquid_flow_raw[:,i]/100,connection_value,'r1-')
    plt.xlabel('Liq. Vel. ($*10^2$ mm/day)')
    # plt.ylabel('high (m)')
    plt.ylim(5.5,-0.5)
    plt.xlim(-5.e-2,1.1)
    #plt.xlim(np.nanmin(Liquid_flow_raw),np.nanmax(Liquid_flow_raw))	
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    ax4.spines['right'].set_color('red')	
    ax4.xaxis.label.set_color('red')
    ax4.tick_params(axis='x', colors='red')	 	
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))    

    ax3=plt.subplot(336)
    ax3.plot(Vapor_pressure[:,i]/Pa2Kpa,element_value,'k1-')
    plt.xlabel('Vap. pre. (Kpa)')
    # plt.ylabel('high (m)')
    plt.ylim(5.5,-0.5)
    plt.xlim(1,1.6)
    #plt.xlim(np.min(Gas_flow_raw),np.max(Gas_flow_raw))
    #ax3.set_yscale('log')
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))	
    ax4=ax3.twiny()	
    ax4.plot(Vapor_diff_flow_raw[:,i]*100,connection_value,'r1-')
    plt.xlabel('Vpa. Dif. ($*10^-2$ mm/day)')
    # plt.ylabel('high (m)')
    plt.ylim(5.5,-0.5)
    plt.xlim(-1,13)
    #plt.xlim(np.nanmin(Liquid_flow_raw),np.nanmax(Liquid_flow_raw))	
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    ax4.spines['right'].set_color('red')	
    ax4.xaxis.label.set_color('red')
    ax4.tick_params(axis='x', colors='red')	 	
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))    


    # ax1=plt.subplot(345)
    # ax1.plot(First_thermodynamic_var[:,i], element_value,'b1-')
    # plt.xlabel('Fir. Var.')
    # #ax1.spines['top'].set_color('red')
    # plt.ylabel('x (m)')
    # plt.ylim(5.5,-0.5)
    # #plt.xlim(50,400)
    # plt.xlim(np.min(First_thermodynamic_var),np.max(First_thermodynamic_var))
    # plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    # #ax1.set_yscale('log')
    # ax2=ax1.twiny()
    # ax2.plot(First_thermodynamic_change[:,i],element_value,'r1-')
    # plt.xlabel('Fst. Cha.')
    # # plt.ylabel('high (m)')
    # plt.ylim(5.5,-0.5)
    # #plt.xlim(-5.e4,1.e3)
    # plt.xlim(np.min(First_thermodynamic_change),np.max(First_thermodynamic_change))
    # #ax2.set_yscale('log')
    # plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    # ax2.spines['top'].set_color('red')
    # ax2.xaxis.label.set_color('red')
    # ax2.tick_params(axis='x', colors='red')	 
    
    # ax11=plt.subplot(346)
    # ax11.plot(Second_thermodynamic_var[:,i],element_value,'b1-')
    # plt.xlabel('Sec. Var.')
    # # plt.ylabel('high (m)')
    # plt.ylim(5.5,-0.5)
    # #plt.xlim(-5,105)
    # plt.xlim(np.min(Second_thermodynamic_var),np.max(Second_thermodynamic_var))
    # #ax11.set_yscale('log')   
    # ax13=ax11.twiny()	
    # ax13.plot(Second_thermodynamic_change[:,i],element_value,'r1-')
    # plt.xlabel('Sec. Cha.')
    # # plt.ylabel('high (m)')
    # plt.ylim(5.5,-0.5)
    # #plt.xlim(12.95,13.05)
    # plt.xlim(np.min(Second_thermodynamic_change),np.max(Second_thermodynamic_change))
    # #ax13.set_yscale('log')
    # plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0)) 
    # ax13.spines['top'].set_color('red')
    # ax13.xaxis.label.set_color('red')
    # ax13.tick_params(axis='x', colors='red')
	
    # ax9=plt.subplot(347)
    # ax9.plot(Third_thermodynamic_var[:,i],element_value,'b1-')
    # #plt.ylabel('x (m)')
    # plt.xlabel('Thi. Var.')
    # # plt.ylabel('high (m)')
    # plt.ylim(5.5,-0.5)
    # #plt.xlim(-5,105)
    # plt.xlim(np.min(Third_thermodynamic_var),np.max(Third_thermodynamic_var))
    # plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0)) 
    # ax10=ax9.twiny()	
    # ax10.plot(Third_thermodynamic_change[:,i],element_value,'r1-')
    # plt.xlabel('Thi. Cha.')
    # # plt.ylabel('high (m)')
    # plt.ylim(5.5,-0.5)
    # #plt.xlim(12.95,13.05)
    # plt.xlim(np.min(Third_thermodynamic_change),np.max(Third_thermodynamic_change))
    # #ax13.set_yscale('log')
    # plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0)) 
    # ax10.spines['top'].set_color('red')
    # ax10.xaxis.label.set_color('red')
    # ax10.tick_params(axis='x', colors='red')

    # ax3=plt.subplot(348)
    # ax3.plot(GAS_H[:,i],element_value,'b1-')
    # plt.xlabel('Gas H')
    # # plt.ylabel('high (m)')
    # plt.ylim(5.5,-0.5)
    # #plt.xlim(-1.2e-1,1.e-2)
    # plt.xlim(np.min(GAS_H),np.max(GAS_H))
    # #ax3.set_yscale('log')
    # plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))	
    # ax4=ax3.twiny()	
    # ax4.plot(Liq_H[:,i],element_value,'r1-')
    # plt.xlabel('Liq. H')
    # # plt.ylabel('high (m)')
    # plt.ylim(5.5,-0.5)
    # #plt.xlim(-5.,1.1e2)
    # plt.xlim(np.nanmin(Liq_H),np.nanmax(Liq_H))	
    # plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    # ax4.spines['right'].set_color('red')	
    # ax4.xaxis.label.set_color('red')
    # ax4.tick_params(axis='x', colors='red')	 	
    # plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))    
	
    ax5=plt.subplot(615)
    ax5.plot(lst.times[:i+1]/day2s,Gas_mass[:i+1],'k1-')
    plt.ylabel('Gas. mass (kg)')
    #plt.xlabel('Time (s)')
    plt.ylim(0,6.e-2)
    #plt.ylim(np.min(Gas_mass),np.max(Gas_mass))
    plt.xlim(0,np.max(lst.times)/day2s)
    ax5.set_xscale('log')
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0),useLocale=0)
    #ax1.spines['left'].set_color('blue')
    ax6 = ax5.twinx() 
    ax6.plot(lst.times[:i+1]/day2s,liquid_mass[:i+1],'r1-',)
    plt.ylim(1300,1340)
    #plt.ylim(np.min(liquid_mass),np.max(liquid_mass))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ylabel('Liq. mass (kg)')
    #plt.xlabel('Time (s)')
    ax6.set_xscale('log')
    ax6.spines['right'].set_color('red')
    ax6.yaxis.label.set_color('red')
    ax6.tick_params(axis='y', colors='red')	 	
	
    ax7=plt.subplot(616)
    ax7.plot(lst.times[:i+1]/day2s,Vapor_diff_flow_topsoil[:i+1],'k1-')
    plt.ylabel('Gas Dar. vel. (mm/day)')
    #plt.xlabel('Time (s)')
    plt.ylim(0.06,0.13)
    #plt.ylim(np.min(Vapor_diff_flow_topsoil),np.max(Vapor_diff_flow_topsoil))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    ax7.set_xscale('log')
    ax8 = ax7.twinx() 
    ax8.plot(lst.times[:i+1]/day2s,Liquid_flow_topsoil[:i+1],'r1-',)
    plt.ylim(-1.e1,1.1e2)
    #plt.ylim(np.min(Liquid_flow_topsoil),np.max(Liquid_flow_topsoil))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    plt.ylabel('Liq. Dar. vel. (mm/day)')
    plt.xlabel('Time (day)')
    ax8.set_xscale('log')
    ax8.spines['right'].set_color('red')
    ax8.yaxis.label.set_color('red')
    ax8.tick_params(axis='y', colors='red')		
	
    fig.suptitle('time: %6.2e s' %lst.times[i])
    plt.rcParams.update({'font.size':12})
    #fig.tight_layout()
    plt.savefig('figure/output_'+str(i+101)+'.png',dpi=300) 
    i+=1

#plt.close('all')