
from t2listing import *
import numpy as np
import matplotlib.pyplot as plt
import csv
import os
from t2data import *
from mpl_toolkits.mplot3d import Axes3D

if not os.path.exists('figure'):
        os.makedirs('figure')

liquid_density_kgPm3=1000
water_molecular_weight=0.018
r_value=8.314
m2mm=1000
day2s=3600*24
t_kelven=273.15
pa2kpa=1000

i=0
while i<lst.num_times:

    fig=plt.figure(figsize=(13,15))
    fig.subplots_adjust(hspace=.30,wspace=.2)
    fig.subplots_adjust(left=0.07, right=0.93, top=0.93, bottom=0.05)
	
    ax11=plt.subplot(341)
    ax11.plot(liq_saturation[:,i]*100,element_value,'k1-')
    plt.ylabel('x (m)')
    plt.xlabel('Liq. sat. (%)')
    # plt.ylabel('high (m)')
    plt.ylim(1.5,-0.1)
    plt.xlim(-5,105)
    #ax11.set_yscale('log')   
    ax13=ax11.twiny()	
    ax13.plot(temperature_degree[:,i],element_value,'r1-')
    plt.xlabel('Tem. (Degree)')
    # plt.ylabel('high (m)')
    plt.ylim(1.5,-0.1)
    plt.xlim(12.95,13.05)
    #plt.xlim(np.min(temperature_degree),np.max(temperature_degree))
    #ax13.set_yscale('log')
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0)) 
    ax13.spines['top'].set_color('red')
    ax13.xaxis.label.set_color('red')
    ax13.tick_params(axis='x', colors='red')

    ax1=plt.subplot(342)
    ax1.plot(gas_pressure_pa[:,i]/pa2kpa, element_value,'k1-')
    plt.xlabel('Gas. Pre. (Kpa)')
    #ax1.spines['top'].set_color('red')
    plt.ylim(1.5,-0.1)
    #plt.xlim(100,115)
    plt.xlim(np.min(gas_pressure_pa/pa2kpa),np.max(gas_pressure_pa/pa2kpa))
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    #ax1.set_yscale('log')
    ax2=ax1.twiny()
    ax2.plot(gas_flow_mmPday[:,i],connection_value,'r1-')
    plt.xlabel('Gas Vel. (mm/day)')
    # plt.ylabel('high (m)')
    plt.ylim(1.5,-0.1)
    #plt.xlim(-100,0.1)
    plt.xlim(np.min(gas_flow_mmPday),np.max(gas_flow_mmPday))
    #ax2.set_yscale('log')
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    ax2.spines['top'].set_color('red')
    ax2.xaxis.label.set_color('red')
    ax2.tick_params(axis='x', colors='red')	 

    ax3=plt.subplot(343)
    ax3.plot(capillary_pressure_pa[:,i]/pa2kpa,element_value,'k1-')
    plt.xlabel('Cap. pre. (Kpa)')
    # plt.ylabel('high (m)')
    plt.ylim(1.5,-0.1)
    #plt.xlim(-50,0.1)
    plt.xlim(np.min(capillary_pressure_pa/pa2kpa),np.max(capillary_pressure_pa/pa2kpa))
    #ax3.set_yscale('log')
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))	
    ax4=ax3.twiny()	
    ax4.plot(liquid_flow_mmPday[:,i],connection_value,'r1-')
    plt.xlabel('Liq. Vel. (mm/day)')
    # plt.ylabel('high (m)')
    plt.ylim(1.5,-0.1)
    #plt.xlim(-5.e-2,1.1)
    plt.xlim(np.nanmin(liquid_flow_mmPday),np.nanmax(liquid_flow_mmPday))	
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    ax4.spines['top'].set_color('red')	
    ax4.xaxis.label.set_color('red')
    ax4.tick_params(axis='x', colors='red')	 	
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))    

    ax3=plt.subplot(344)
    ax3.plot(vapor_pressure_pa[:,i]/pa2kpa,element_value,'k1-')
    plt.xlabel('Vap. pre. (Kpa)')
    # plt.ylabel('high (m)')
    plt.ylim(1.5,-0.1)
    #plt.xlim(1,1.6)
    plt.xlim(np.min(vapor_pressure_pa/pa2kpa),np.max(vapor_pressure_pa/pa2kpa))
    #ax3.set_yscale('log')
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))	
    ax4=ax3.twiny()	
    ax4.plot(vapor_diff_flow_mmPday[:,i],connection_value,'r1-')
    plt.xlabel('Vpa. Dif. (mm/day)')
    # plt.ylabel('high (m)')
    plt.ylim(1.5,-0.1)
    #plt.xlim(-0.1,1.3)
    plt.xlim(np.nanmin(vapor_diff_flow_mmPday),np.nanmax(vapor_diff_flow_mmPday))	
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
    ax4.spines['top'].set_color('red')	
    ax4.xaxis.label.set_color('red')
    ax4.tick_params(axis='x', colors='red')	 	
    #plt.ticklabel_format(style='sci', axis='x', scilimits=(0,0))    

    ax7=plt.subplot(613)
    ax7.plot(lst.times[:i+1]/day2s,vapor_diff_flow_top_mmPday[:i+1],'k1-')
    plt.ylabel('Vap. Dif. Top(mm/day)')
    #plt.xlabel('Time (day)')
    #plt.ylim(0.08,0.13)
    plt.ylim(np.min(vapor_diff_flow_top_mmPday),np.max(vapor_diff_flow_top_mmPday))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    #ax7.set_xscale('log')
    ax8 = ax7.twinx() 
    ax8.plot(lst.times[:i+1]/day2s,vapor_adv_flow_top_mmPday[:i+1],'r1-',)
    #plt.ylim(-1.3e-1,-6e-2)
    plt.ylim(np.min(vapor_adv_flow_top_mmPday),np.max(vapor_adv_flow_top_mmPday))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    plt.ylabel('Vap. Adv. Top(mm/day)')
    #plt.xlabel('Time (day)')
    #ax8.set_xscale('log')
    ax8.spines['right'].set_color('red')
    ax8.yaxis.label.set_color('red')
    ax8.tick_params(axis='y', colors='red')
	
    ax7=plt.subplot(614)
    ax7.plot(lst.times[:i+1]/day2s,vapor_flow_top_mmPday[:i+1],'k1-')
    plt.ylabel('Vap. Vel. Top(mm/day)')
    plt.xlabel('Time (day)')
    #plt.ylim(-0.1e-3,0.11e-2)
    plt.ylim(np.min(vapor_flow_top_mmPday),np.max(vapor_flow_top_mmPday))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    #ax7.set_xscale('log')
    ax8 = ax7.twinx() 
    ax8.plot(lst.times[:i+1]/day2s,liquid_flow_top_mmPday[:i+1],'r1-',)
    #plt.ylim(-1.e1,1.1e2)
    plt.ylim(np.min(liquid_flow_top_mmPday),np.max(liquid_flow_top_mmPday))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    plt.ylabel('Liq. Vel. Top(mm/day)')
    plt.xlabel('Time (day)')
    #ax8.set_xscale('log')
    ax8.spines['right'].set_color('red')
    ax8.yaxis.label.set_color('red')
    ax8.tick_params(axis='y', colors='red')		
	
    ax7=plt.subplot(615)
    ax7.plot(lst.times[:i+1]/day2s,vapor_diff_flow_second_mmPday[:i+1],'k1-')
    plt.ylabel('Vap. Dif. Sec. (mm/day)')
    #plt.xlabel('Time (day)')
    #plt.ylim(0.08,0.13)
    plt.ylim(np.min(vapor_diff_flow_second_mmPday),np.max(vapor_diff_flow_second_mmPday))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    #ax7.set_xscale('log')
    ax8 = ax7.twinx() 
    ax8.plot(lst.times[:i+1]/day2s,vapor_adv_flow_second_mmPday[:i+1],'r1-',)
    #plt.ylim(-1.3e-1,-6e-2)
    plt.ylim(np.min(vapor_adv_flow_second_mmPday),np.max(vapor_adv_flow_second_mmPday))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    plt.ylabel('Vap. Adv. Sec. (mm/day)')
    #plt.xlabel('Time (day)')
    #ax8.set_xscale('log')
    ax8.spines['right'].set_color('red')
    ax8.yaxis.label.set_color('red')
    ax8.tick_params(axis='y', colors='red')
	
    ax7=plt.subplot(616)
    ax7.plot(lst.times[:i+1]/day2s,vapor_flow_second_mmPday[:i+1],'k1-')
    plt.ylabel('Vap. Vel. Sec. (mm/day)')
    plt.xlabel('Time (day)')
    #plt.ylim(-0.1e-3,0.11e-2)
    plt.ylim(np.min(vapor_flow_second_mmPday),np.max(vapor_flow_second_mmPday))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    #ax7.set_xscale('log')
    ax8 = ax7.twinx() 
    ax8.plot(lst.times[:i+1]/day2s,liquid_flow_second_mmPday[:i+1],'r1-',)
    #plt.ylim(-1.e1,1.1e2)
    plt.ylim(np.min(liquid_flow_second_mmPday),np.max(liquid_flow_second_mmPday))
    plt.xlim(0,np.max(lst.times)/day2s)
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    plt.ylabel('Liq. Vel. Sec. (mm/day)')
    plt.xlabel('Time (day)')
    #ax8.set_xscale('log')
    ax8.spines['right'].set_color('red')
    ax8.yaxis.label.set_color('red')
    ax8.tick_params(axis='y', colors='red')			
	
    fig.suptitle('time: %6.2e s' %lst.times[i])
    plt.rcParams.update({'font.size':12})
    #fig.tight_layout()
    plt.savefig('figure/output_'+str(i+101)+'.png',dpi=300) 
    i+=1

#plt.close('all')